### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ixs** [mendix/pmCommand.py#1]
Hi,

I needed to do some work on an avocent PDU which has a slightly different but mostly similar API to the one you've implemented here.

I had hoped to use your code as the basis for my tool, but the license is unclear.
Code says "all rights reserved" which does not allow for any modification.

Would it be possible to clarify the license the code is under?

thanks.

**Comment by knorrie** [comment]
Hi Andreas,

Sure. I'll push a commit RSN to make it MIT license and clean up the headers of the files. Go ahead, use it now.

The fact that the latest commit is from 2014 (whoa, 6 years ago) does not mean it's unmaintained, it just has been working fine all the time.

Well, actually, the latest available (abandoned) software (https, TLS, ciphers) in the avocent ACS and PDU is incompatible with recent OS versions now. You already can't open the https page in any recent browser any more.

My TODO list contains a few tasks to change this program to take a url instead of an ip address (so that you can use http:// instead of hardcoded https://) and also look if there's anything else needed to point this to one or more PDUs directly (and combine the ports of them), instead of connecting to the ACS which connects to the PDUs again.

So, yes, by all means, use it. It's reverse engineered xslt xml stuff, but it's better than nothing. It's python 2.7 code which looks like how I did stuff 6 years ago, the git log is quite yolo, but the actual result is not that bad at all.

If you have more questions, just ask.

Thanks,
Hans

**Comment by knorrie** [comment]
I added a LICENSE file. Have fun!

**Comment by ixs** [comment]
@knorrie Have a look at https://gist.github.com/ixs/58381ed5f8109b6a988a2eb06036b348 which is a tampermonkey script that makes the webinterface work again by readding the legacy javascript functions.

**Comment by ixs** [comment]
In other news, I opened two pull requests that might take care of your two TODO items... partly at least...
